"""Seed Data：真实 AI/ML 领域知识节点与关系。

数据为真实、公开的世界知识（Wikipedia / arXiv），用于验证数据库与图结构。
字段约定：
  NODES    -> (id, name, category, description, source, source_url)
  RELATIONS -> (source_id, target_id, relation_type)

relation_type 词表：
  subfield_of  A 是 B 的子领域
  is_a         A 是 B 的一种
  part_of      A 是 B 的组成部分
  used_in      A 被用于 B
  based_on     A 基于 B
  related_to   A 与 B 相关
"""

NODES = [
    # ---------- field（领域） ----------
    ("artificial-intelligence", "Artificial Intelligence", "field",
     "The study and engineering of intelligent agents and systems that perceive their environment and take actions to achieve goals, encompassing learning, reasoning, and perception.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Artificial_intelligence"),
    ("machine-learning", "Machine Learning", "field",
     "A subfield of artificial intelligence focused on algorithms that improve automatically through experience and data, without being explicitly programmed.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Machine_learning"),
    ("deep-learning", "Deep Learning", "field",
     "A branch of machine learning based on artificial neural networks with multiple layers that learn hierarchical representations of data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Deep_learning"),
    ("natural-language-processing", "Natural Language Processing", "field",
     "A field of AI concerned with giving computers the ability to understand and generate human language.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Natural_language_processing"),
    ("computer-vision", "Computer Vision", "field",
     "A field of AI that enables machines to interpret and understand visual information from images and video.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Computer_vision"),
    ("reinforcement-learning", "Reinforcement Learning", "field",
     "A machine learning paradigm in which an agent learns to make decisions by interacting with an environment and receiving rewards or penalties.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Reinforcement_learning"),
    ("generative-ai", "Generative AI", "field",
     "AI systems capable of generating new content such as text, images, and audio, typically built on deep generative models.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Generative_artificial_intelligence"),
    ("data-science", "Data Science", "field",
     "An interdisciplinary field that uses scientific methods, statistics, and computation to extract knowledge and insight from data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Data_science"),

    # ---------- paradigm（学习范式） ----------
    ("supervised-learning", "Supervised Learning", "paradigm",
     "Learning from labeled examples where the model maps inputs to known target outputs.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Supervised_learning"),
    ("unsupervised-learning", "Unsupervised Learning", "paradigm",
     "Learning patterns and structure from unlabeled data without explicit target outputs.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Unsupervised_learning"),
    ("semi-supervised-learning", "Semi-supervised Learning", "paradigm",
     "Learning that combines a small amount of labeled data with a large amount of unlabeled data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Semi-supervised_learning"),
    ("self-supervised-learning", "Self-supervised Learning", "paradigm",
     "A paradigm where models learn representations by solving pretext tasks derived from the data itself, without manual labels.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Self-supervised_learning"),
    ("transfer-learning", "Transfer Learning", "paradigm",
     "Reusing knowledge learned on one task or domain to improve learning on another related task or domain.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Transfer_learning"),

    # ---------- algorithm（经典算法） ----------
    ("linear-regression", "Linear Regression", "algorithm",
     "A simple model that predicts a continuous target as a linear combination of input features.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Linear_regression"),
    ("logistic-regression", "Logistic Regression", "algorithm",
     "A classification model that estimates probabilities using a logistic function of a linear feature combination.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Logistic_regression"),
    ("decision-tree", "Decision Tree", "algorithm",
     "A model that makes predictions by recursively splitting data according to feature values, forming a tree structure.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Decision_tree_learning"),
    ("random-forest", "Random Forest", "algorithm",
     "An ensemble of decision trees trained on random subsets of data and features, combined by voting or averaging.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Random_forest"),
    ("support-vector-machine", "Support Vector Machine", "algorithm",
     "A classifier that finds the hyperplane maximizing the margin between classes.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Support_vector_machine"),
    ("k-nearest-neighbors", "k-Nearest Neighbors", "algorithm",
     "A lazy learning method that classifies or regresses based on the k closest training examples.",
     "Wikipedia", "https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm"),
    ("naive-bayes", "Naive Bayes", "algorithm",
     "A probabilistic classifier applying Bayes' theorem with the assumption of conditional independence between features.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Naive_Bayes_classifier"),
    ("gradient-boosting", "Gradient Boosting", "algorithm",
     "An ensemble technique that builds weak learners sequentially, each correcting the residual errors of the previous ones.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Gradient_boosting"),
    ("xgboost", "XGBoost", "algorithm",
     "An optimized, scalable implementation of gradient-boosted decision trees widely used for tabular data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/XGBoost"),
    ("k-means", "k-Means Clustering", "algorithm",
     "An unsupervised algorithm that partitions data into k clusters by iteratively updating centroids.",
     "Wikipedia", "https://en.wikipedia.org/wiki/K-means_clustering"),
    ("principal-component-analysis", "Principal Component Analysis", "algorithm",
     "A dimensionality reduction method that projects data onto orthogonal directions of maximum variance.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Principal_component_analysis"),
    ("ensemble-learning", "Ensemble Learning", "algorithm",
     "Combining multiple models to produce a single, usually more robust and accurate predictor.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Ensemble_learning"),
    ("hidden-markov-model", "Hidden Markov Model", "algorithm",
     "A probabilistic model of sequences with unobserved states and observed emissions, used for temporal data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Hidden_Markov_model"),

    # ---------- neural-network foundations ----------
    ("artificial-neural-network", "Artificial Neural Network", "concept",
     "A computational model composed of connected units (neurons) loosely inspired by biological brains.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Neural_network_(machine_learning)"),
    ("perceptron", "Perceptron", "model",
     "The simplest artificial neuron model; a linear binary classifier trained by a weight-update rule.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Perceptron"),
    ("multilayer-perceptron", "Multilayer Perceptron", "model",
     "A feedforward neural network with one or more hidden layers between input and output.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Multilayer_perceptron"),
    ("activation-function", "Activation Function", "concept",
     "A nonlinear function applied to neuron outputs that enables networks to model complex mappings.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Activation_function"),
    ("backpropagation", "Backpropagation", "algorithm",
     "The algorithm that computes gradients of a loss with respect to weights by applying the chain rule backward through the network.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Backpropagation"),
    ("gradient-descent", "Gradient Descent", "algorithm",
     "An optimization algorithm that iteratively moves parameters in the direction of steepest descent of a loss function.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Gradient_descent"),
    ("loss-function", "Loss Function", "concept",
     "A function measuring the discrepancy between model predictions and targets, minimized during training.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Loss_function"),
    ("dropout", "Dropout", "technique",
     "A regularization technique that randomly drops units during training to reduce overfitting.",
     "arXiv", "https://arxiv.org/abs/1207.0580"),
    ("batch-normalization", "Batch Normalization", "technique",
     "A technique that normalizes layer inputs per mini-batch to stabilize and accelerate training.",
     "arXiv", "https://arxiv.org/abs/1502.03167"),
    ("regularization", "Regularization", "technique",
     "Techniques that constrain model complexity to improve generalization and prevent overfitting.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Regularization_(mathematics)"),
    ("overfitting", "Overfitting", "concept",
     "When a model fits training data too closely and fails to generalize to unseen data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Overfitting"),
    ("underfitting", "Underfitting", "concept",
     "When a model is too simple to capture the underlying patterns in the data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Overfitting"),
    ("adam", "Adam", "algorithm",
     "A popular adaptive learning-rate optimization algorithm combining momentum and per-parameter scaling.",
     "arXiv", "https://arxiv.org/abs/1412.6980"),

    # ---------- deep architectures ----------
    ("convolutional-neural-network", "Convolutional Neural Network", "architecture",
     "A network using convolutional filters to learn spatial hierarchies of features, dominant in computer vision.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Convolutional_neural_network"),
    ("resnet", "ResNet", "architecture",
     "A deep CNN introducing skip (residual) connections that ease training of very deep networks.",
     "arXiv", "https://arxiv.org/abs/1512.03385"),
    ("densenet", "DenseNet", "architecture",
     "A CNN where each layer is connected to every subsequent layer via dense skip connections.",
     "arXiv", "https://arxiv.org/abs/1608.06993"),
    ("efficientnet", "EfficientNet", "architecture",
     "A family of CNNs scaled systematically across depth, width, and resolution for efficiency.",
     "arXiv", "https://arxiv.org/abs/1905.11946"),
    ("mobilenet", "MobileNet", "architecture",
     "Lightweight CNN architectures using depthwise separable convolutions for mobile and embedded devices.",
     "arXiv", "https://arxiv.org/abs/1704.04861"),
    ("u-net", "U-Net", "architecture",
     "A CNN with an encoder-decoder structure and skip connections, widely used for image segmentation.",
     "arXiv", "https://arxiv.org/abs/1505.04597"),
    ("recurrent-neural-network", "Recurrent Neural Network", "architecture",
     "A network that processes sequences by maintaining a hidden state that carries information across time steps.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Recurrent_neural_network"),
    ("lstm", "LSTM", "architecture",
     "Long Short-Term Memory; an RNN variant using gating to learn long-range dependencies.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Long_short-term_memory"),
    ("gru", "GRU", "architecture",
     "Gated Recurrent Unit; a gated RNN variant with a simplified gating mechanism compared to LSTM.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Gated_recurrent_unit"),
    ("transformer", "Transformer", "architecture",
     "A neural architecture based entirely on attention, eliminating recurrence and enabling parallel sequence processing.",
     "arXiv", "https://arxiv.org/abs/1706.03762"),
    ("attention-mechanism", "Attention Mechanism", "concept",
     "A technique that lets models weight the importance of different parts of the input when producing each output.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Attention_(machine_learning)"),
    ("self-attention", "Self-Attention", "concept",
     "Attention computed within a single sequence, relating each element to all others.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Attention_(machine_learning)"),
    ("multi-head-attention", "Multi-Head Attention", "concept",
     "Running multiple attention operations in parallel to capture different relationship subspaces.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Attention_(machine_learning)"),
    ("bert", "BERT", "model",
     "A transformer encoder pre-trained with masked language modeling, strong for language understanding tasks.",
     "arXiv", "https://arxiv.org/abs/1810.04805"),
    ("gpt", "GPT", "model",
     "A family of transformer decoder language models pre-trained autoregressively to predict the next token.",
     "Wikipedia", "https://en.wikipedia.org/wiki/GPT-3"),
    ("vision-transformer", "Vision Transformer", "architecture",
     "A transformer applied to image patches, showing that attention alone can achieve strong vision results.",
     "arXiv", "https://arxiv.org/abs/2010.11929"),
    ("generative-adversarial-network", "Generative Adversarial Network", "architecture",
     "A generative framework where a generator and a discriminator are trained adversarially against each other.",
     "arXiv", "https://arxiv.org/abs/1406.2661"),
    ("variational-autoencoder", "Variational Autoencoder", "architecture",
     "A generative model that learns a probabilistic latent representation of data.",
     "arXiv", "https://arxiv.org/abs/1312.6114"),
    ("diffusion-model", "Diffusion Model", "architecture",
     "A generative model that learns to reverse a gradual noising process to synthesize data.",
     "arXiv", "https://arxiv.org/abs/2006.11239"),
    ("autoencoder", "Autoencoder", "architecture",
     "A network trained to reconstruct its input through a compressed bottleneck, learning compact representations.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Autoencoder"),
    ("graph-neural-network", "Graph Neural Network", "architecture",
     "A network that operates on graph-structured data by aggregating information from neighboring nodes.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Graph_neural_network"),
    ("sequence-to-sequence", "Sequence-to-Sequence", "architecture",
     "A framework that maps an input sequence to an output sequence, often with encoder-decoder networks.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Seq2seq"),
    ("large-language-model", "Large Language Model", "model",
     "A language model with billions of parameters, typically transformer-based, trained on massive text corpora.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Large_language_model"),

    # ---------- computer vision tasks ----------
    ("image-classification", "Image Classification", "task",
     "Assigning a single category label to an input image.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Computer_vision"),
    ("object-detection", "Object Detection", "task",
     "Locating and classifying multiple objects within an image, typically with bounding boxes.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Object_detection"),
    ("semantic-segmentation", "Semantic Segmentation", "task",
     "Assigning a class label to every pixel in an image.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Image_segmentation"),
    ("instance-segmentation", "Instance Segmentation", "task",
     "Detecting individual object instances and segmenting each one at the pixel level.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Image_segmentation"),
    ("yolo", "YOLO", "model",
     "A real-time object detection approach framing detection as a single regression problem.",
     "arXiv", "https://arxiv.org/abs/1506.02640"),
    ("feature-pyramid-network", "Feature Pyramid Network", "architecture",
     "An architecture that builds multi-scale feature maps to improve detection across object sizes.",
     "arXiv", "https://arxiv.org/abs/1612.03144"),
    ("image-generation", "Image Generation", "task",
     "Synthesizing new images, typically via generative models such as GANs or diffusion models.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Artificial_intelligence_art"),
    ("pose-estimation", "Pose Estimation", "task",
     "Estimating the positions of key body joints or object parts from visual input.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Pose_(computer_vision)"),
    ("image-captioning", "Image Captioning", "task",
     "Generating natural language descriptions of the content of an image.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Image_captioning"),

    # ---------- NLP ----------
    ("tokenization", "Tokenization", "concept",
     "Splitting text into smaller units (tokens) such as words or subwords for processing.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Lexical_analysis"),
    ("word-embedding", "Word Embedding", "concept",
     "Dense vector representations of words that capture semantic and syntactic relationships.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Word_embedding"),
    ("word2vec", "Word2Vec", "model",
     "A method that learns word embeddings by predicting context words from a target word (or vice versa).",
     "arXiv", "https://arxiv.org/abs/1301.3781"),
    ("glove", "GloVe", "model",
     "Global Vectors; word embeddings learned from global word co-occurrence statistics.",
     "Wikipedia", "https://en.wikipedia.org/wiki/GloVe"),
    ("named-entity-recognition", "Named Entity Recognition", "task",
     "Identifying and classifying named entities (people, places, organizations) in text.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Named-entity_recognition"),
    ("sentiment-analysis", "Sentiment Analysis", "task",
     "Determining the sentiment or emotional tone expressed in a piece of text.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Sentiment_analysis"),
    ("machine-translation", "Machine Translation", "task",
     "Automatically translating text from one language to another.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Machine_translation"),
    ("text-classification", "Text Classification", "task",
     "Assigning predefined categories or labels to text documents.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Document_classification"),
    ("language-model", "Language Model", "model",
     "A model that assigns probabilities to sequences of tokens, capturing the statistics of language.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Language_model"),
    ("question-answering", "Question Answering", "task",
     "Systems that automatically answer questions posed in natural language.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Question_answering"),
    ("text-summarization", "Text Summarization", "task",
     "Producing a concise summary of a longer text while preserving key information.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Automatic_summarization"),
    ("fine-tuning", "Fine-tuning", "technique",
     "Further training a pre-trained model on a smaller, task-specific dataset to adapt it.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Fine-tuning_(deep_learning)"),
    ("prompt-engineering", "Prompt Engineering", "technique",
     "Designing inputs to guide a language model's behavior without changing its weights.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Prompt_engineering"),

    # ---------- reinforcement learning ----------
    ("q-learning", "Q-Learning", "algorithm",
     "A model-free reinforcement learning algorithm that learns action values to find an optimal policy.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Q-learning"),
    ("deep-q-network", "Deep Q-Network", "model",
     "Q-learning combined with deep neural networks and experience replay, enabling play from raw pixels.",
     "arXiv", "https://arxiv.org/abs/1312.5602"),
    ("policy-gradient", "Policy Gradient", "algorithm",
     "RL methods that directly optimize the policy by following gradients of expected reward.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Policy_gradient_methods"),
    ("ppo", "PPO", "algorithm",
     "Proximal Policy Optimization; a policy-gradient method using clipped objectives for stable updates.",
     "arXiv", "https://arxiv.org/abs/1707.06347"),
    ("markov-decision-process", "Markov Decision Process", "concept",
     "A formal framework for decision-making with states, actions, rewards, and transition probabilities.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Markov_decision_process"),
    ("actor-critic", "Actor-Critic", "algorithm",
     "RL methods that combine a policy (actor) with a value function (critic).",
     "Wikipedia", "https://en.wikipedia.org/wiki/Actor-critic_algorithm"),
    ("reward", "Reward", "concept",
     "The scalar feedback signal an RL agent receives from the environment to guide learning.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Reinforcement_learning"),

    # ---------- concepts / techniques ----------
    ("embedding", "Embedding", "concept",
     "A learned vector representation of an object (word, image, node) in a continuous space.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Feature_learning"),
    ("vector-database", "Vector Database", "concept",
     "A database optimized to store and query high-dimensional vector embeddings by similarity.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Vector_database"),
    ("semantic-search", "Semantic Search", "concept",
     "Search that matches queries and documents by meaning rather than exact keywords.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Semantic_search"),
    ("similarity-search", "Similarity Search", "concept",
     "Finding items most similar to a query, often via nearest-neighbor search in vector space.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Nearest_neighbor_search"),
    ("cosine-similarity", "Cosine Similarity", "concept",
     "A measure of similarity between vectors based on the cosine of the angle between them.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Cosine_similarity"),
    ("knowledge-graph", "Knowledge Graph", "concept",
     "A structured representation of entities and their relationships, used for search and reasoning.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Knowledge_graph"),
    ("information-retrieval", "Information Retrieval", "concept",
     "The task of obtaining relevant information from a large collection, often via ranking.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Information_retrieval"),
    ("retrieval-augmented-generation", "RAG", "concept",
     "Augmenting a language model's generation with retrieved external knowledge to improve accuracy and grounding.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Retrieval-augmented_generation"),
    ("data-augmentation", "Data Augmentation", "technique",
     "Artificially expanding a training set via transformations to improve generalization.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Data_augmentation"),
    ("cross-validation", "Cross-Validation", "technique",
     "A model evaluation technique that splits data into multiple train/test folds to estimate generalization.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Cross-validation_(statistics)"),
    ("feature-engineering", "Feature Engineering", "technique",
     "Designing and selecting informative input features to improve model performance.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Feature_engineering"),
    ("bias-variance-tradeoff", "Bias-Variance Tradeoff", "concept",
     "The tension between a model's error from oversimplification (bias) and sensitivity to data (variance).",
     "Wikipedia", "https://en.wikipedia.org/wiki/Bias%E2%80%93variance_tradeoff"),
    ("generalization", "Generalization", "concept",
     "A model's ability to perform well on unseen data, not just training data.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Generalization_error"),
    ("learning-rate", "Learning Rate", "concept",
     "A hyperparameter controlling the step size of parameter updates during optimization.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Learning_rate"),
    ("contrastive-learning", "Contrastive Learning", "technique",
     "Learning representations by pulling similar pairs together and pushing dissimilar pairs apart.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Contrastive_learning"),
    ("zero-shot-learning", "Zero-Shot Learning", "technique",
     "Performing a task without any labeled examples of that task, often via transfer or prompting.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Zero-shot_learning"),
    ("few-shot-learning", "Few-Shot Learning", "technique",
     "Learning or adapting from only a few labeled examples.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Few-shot_learning_(natural_language_processing)"),
    ("multimodal-learning", "Multimodal Learning", "paradigm",
     "Learning from multiple modalities of data (e.g., text, image, audio) jointly.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Multimodal_learning"),

    # ---------- datasets / benchmarks ----------
    ("imagenet", "ImageNet", "dataset",
     "A large image database organized by the WordNet hierarchy, foundational for deep learning in vision.",
     "Wikipedia", "https://en.wikipedia.org/wiki/ImageNet"),
    ("mnist", "MNIST", "dataset",
     "A classic dataset of handwritten digits widely used as a benchmark for image classification.",
     "Wikipedia", "https://en.wikipedia.org/wiki/MNIST_database"),
    ("cifar-10", "CIFAR-10", "dataset",
     "A benchmark dataset of 60,000 small color images across 10 object classes.",
     "Wikipedia", "https://en.wikipedia.org/wiki/CIFAR-10"),
    ("squad", "SQuAD", "dataset",
     "Stanford Question Answering Dataset; a reading comprehension benchmark over Wikipedia passages.",
     "Wikipedia", "https://en.wikipedia.org/wiki/SQuAD"),
    ("coco", "COCO", "dataset",
     "Common Objects in Context; a dataset for object detection, segmentation, and captioning.",
     "Wikipedia", "https://en.wikipedia.org/wiki/COCO_(dataset)"),
    ("common-crawl", "Common Crawl", "dataset",
     "A large, openly available web crawl corpus used for training language models.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Common_Crawl"),

    # ---------- applications ----------
    ("recommender-system", "Recommender System", "application",
     "Systems that predict user preferences and suggest relevant items.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Recommender_system"),
    ("autonomous-driving", "Autonomous Driving", "application",
     "Vehicles that perceive and navigate their environment with limited human input, relying on CV and RL.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Self-driving_car"),
    ("speech-recognition", "Speech Recognition", "application",
     "Converting spoken audio into text, often via sequence models.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Speech_recognition"),
    ("anomaly-detection", "Anomaly Detection", "application",
     "Identifying rare or unusual data points that deviate from the norm.",
     "Wikipedia", "https://en.wikipedia.org/wiki/Anomaly_detection"),
]

RELATIONS = [
    # field hierarchy
    ("machine-learning", "artificial-intelligence", "subfield_of"),
    ("deep-learning", "machine-learning", "subfield_of"),
    ("natural-language-processing", "artificial-intelligence", "subfield_of"),
    ("computer-vision", "artificial-intelligence", "subfield_of"),
    ("reinforcement-learning", "artificial-intelligence", "subfield_of"),
    ("generative-ai", "artificial-intelligence", "subfield_of"),
    ("machine-learning", "data-science", "related_to"),
    ("data-science", "artificial-intelligence", "related_to"),
    ("deep-learning", "artificial-neural-network", "based_on"),
    ("generative-ai", "deep-learning", "based_on"),

    # paradigms
    ("supervised-learning", "machine-learning", "is_a"),
    ("unsupervised-learning", "machine-learning", "is_a"),
    ("semi-supervised-learning", "machine-learning", "is_a"),
    ("self-supervised-learning", "machine-learning", "is_a"),
    ("transfer-learning", "machine-learning", "is_a"),
    ("reinforcement-learning", "machine-learning", "is_a"),
    ("ensemble-learning", "machine-learning", "is_a"),

    # classical algorithms -> supervised
    ("linear-regression", "supervised-learning", "is_a"),
    ("logistic-regression", "supervised-learning", "is_a"),
    ("decision-tree", "supervised-learning", "is_a"),
    ("random-forest", "supervised-learning", "is_a"),
    ("support-vector-machine", "supervised-learning", "is_a"),
    ("k-nearest-neighbors", "supervised-learning", "is_a"),
    ("naive-bayes", "supervised-learning", "is_a"),
    ("gradient-boosting", "supervised-learning", "is_a"),
    # classical algorithms -> unsupervised
    ("k-means", "unsupervised-learning", "is_a"),
    ("principal-component-analysis", "unsupervised-learning", "is_a"),
    ("hidden-markov-model", "unsupervised-learning", "is_a"),
    # ensembles
    ("random-forest", "ensemble-learning", "is_a"),
    ("gradient-boosting", "ensemble-learning", "is_a"),
    ("xgboost", "ensemble-learning", "is_a"),
    ("xgboost", "gradient-boosting", "is_a"),
    ("decision-tree", "random-forest", "part_of"),
    ("xgboost", "decision-tree", "based_on"),
    ("gradient-boosting", "decision-tree", "based_on"),

    # neural network foundations
    ("perceptron", "artificial-neural-network", "is_a"),
    ("multilayer-perceptron", "artificial-neural-network", "is_a"),
    ("multilayer-perceptron", "perceptron", "based_on"),
    ("activation-function", "artificial-neural-network", "part_of"),
    ("loss-function", "artificial-neural-network", "part_of"),
    ("backpropagation", "artificial-neural-network", "used_in"),
    ("gradient-descent", "machine-learning", "used_in"),
    ("backpropagation", "gradient-descent", "related_to"),
    ("gradient-descent", "loss-function", "related_to"),
    ("dropout", "regularization", "is_a"),
    ("batch-normalization", "artificial-neural-network", "used_in"),
    ("regularization", "overfitting", "related_to"),
    ("regularization", "machine-learning", "used_in"),
    ("adam", "gradient-descent", "is_a"),
    ("overfitting", "machine-learning", "related_to"),
    ("underfitting", "machine-learning", "related_to"),
    ("cross-validation", "machine-learning", "used_in"),

    # deep architectures
    ("convolutional-neural-network", "deep-learning", "is_a"),
    ("convolutional-neural-network", "artificial-neural-network", "is_a"),
    ("resnet", "convolutional-neural-network", "is_a"),
    ("densenet", "convolutional-neural-network", "is_a"),
    ("efficientnet", "convolutional-neural-network", "is_a"),
    ("mobilenet", "convolutional-neural-network", "is_a"),
    ("u-net", "convolutional-neural-network", "is_a"),
    ("recurrent-neural-network", "artificial-neural-network", "is_a"),
    ("lstm", "recurrent-neural-network", "is_a"),
    ("gru", "recurrent-neural-network", "is_a"),
    ("transformer", "deep-learning", "is_a"),
    ("transformer", "artificial-neural-network", "is_a"),
    ("transformer", "self-attention", "based_on"),
    ("attention-mechanism", "transformer", "part_of"),
    ("self-attention", "attention-mechanism", "is_a"),
    ("multi-head-attention", "self-attention", "based_on"),
    ("multi-head-attention", "attention-mechanism", "part_of"),
    ("bert", "transformer", "is_a"),
    ("gpt", "transformer", "is_a"),
    ("vision-transformer", "transformer", "is_a"),
    ("large-language-model", "transformer", "based_on"),
    ("gpt", "large-language-model", "is_a"),
    ("bert", "large-language-model", "is_a"),
    ("autoencoder", "artificial-neural-network", "is_a"),
    ("variational-autoencoder", "autoencoder", "based_on"),
    ("graph-neural-network", "deep-learning", "is_a"),
    ("sequence-to-sequence", "deep-learning", "is_a"),
    ("sequence-to-sequence", "recurrent-neural-network", "based_on"),
    ("transformer", "sequence-to-sequence", "related_to"),
    ("generative-adversarial-network", "generative-ai", "used_in"),
    ("variational-autoencoder", "generative-ai", "used_in"),
    ("diffusion-model", "generative-ai", "used_in"),

    # computer vision tasks
    ("image-classification", "computer-vision", "is_a"),
    ("object-detection", "computer-vision", "is_a"),
    ("semantic-segmentation", "computer-vision", "is_a"),
    ("instance-segmentation", "computer-vision", "is_a"),
    ("image-generation", "computer-vision", "is_a"),
    ("pose-estimation", "computer-vision", "is_a"),
    ("image-captioning", "computer-vision", "is_a"),
    ("image-captioning", "natural-language-processing", "related_to"),
    ("yolo", "object-detection", "is_a"),
    ("feature-pyramid-network", "object-detection", "used_in"),
    ("u-net", "semantic-segmentation", "used_in"),
    ("resnet", "image-classification", "used_in"),
    ("convolutional-neural-network", "image-classification", "used_in"),
    ("convolutional-neural-network", "computer-vision", "used_in"),
    ("vision-transformer", "computer-vision", "used_in"),
    ("transformer", "computer-vision", "used_in"),
    ("diffusion-model", "image-generation", "used_in"),
    ("generative-adversarial-network", "image-generation", "used_in"),
    ("semantic-segmentation", "instance-segmentation", "related_to"),

    # NLP
    ("tokenization", "natural-language-processing", "part_of"),
    ("word-embedding", "natural-language-processing", "used_in"),
    ("word2vec", "word-embedding", "is_a"),
    ("glove", "word-embedding", "is_a"),
    ("named-entity-recognition", "natural-language-processing", "is_a"),
    ("sentiment-analysis", "natural-language-processing", "is_a"),
    ("machine-translation", "natural-language-processing", "is_a"),
    ("text-classification", "natural-language-processing", "is_a"),
    ("language-model", "natural-language-processing", "used_in"),
    ("question-answering", "natural-language-processing", "is_a"),
    ("text-summarization", "natural-language-processing", "is_a"),
    ("fine-tuning", "transfer-learning", "is_a"),
    ("prompt-engineering", "large-language-model", "used_in"),
    ("bert", "named-entity-recognition", "used_in"),
    ("bert", "sentiment-analysis", "used_in"),
    ("gpt", "question-answering", "used_in"),
    ("transformer", "machine-translation", "used_in"),
    ("transformer", "natural-language-processing", "used_in"),
    ("machine-translation", "sequence-to-sequence", "related_to"),
    ("word2vec", "self-supervised-learning", "is_a"),

    # reinforcement learning
    ("q-learning", "reinforcement-learning", "is_a"),
    ("deep-q-network", "q-learning", "based_on"),
    ("policy-gradient", "reinforcement-learning", "is_a"),
    ("ppo", "policy-gradient", "is_a"),
    ("actor-critic", "reinforcement-learning", "is_a"),
    ("ppo", "actor-critic", "based_on"),
    ("markov-decision-process", "reinforcement-learning", "part_of"),
    ("reward", "markov-decision-process", "part_of"),
    ("reward", "reinforcement-learning", "part_of"),
    ("deep-q-network", "deep-learning", "based_on"),

    # concepts / techniques
    ("embedding", "deep-learning", "used_in"),
    ("word-embedding", "embedding", "is_a"),
    ("embedding", "semantic-search", "used_in"),
    ("similarity-search", "semantic-search", "part_of"),
    ("cosine-similarity", "similarity-search", "used_in"),
    ("vector-database", "similarity-search", "used_in"),
    ("vector-database", "semantic-search", "used_in"),
    ("knowledge-graph", "information-retrieval", "used_in"),
    ("knowledge-graph", "artificial-intelligence", "related_to"),
    ("retrieval-augmented-generation", "large-language-model", "used_in"),
    ("retrieval-augmented-generation", "information-retrieval", "based_on"),
    ("retrieval-augmented-generation", "semantic-search", "used_in"),
    ("retrieval-augmented-generation", "knowledge-graph", "related_to"),
    ("semantic-search", "information-retrieval", "is_a"),
    ("similarity-search", "information-retrieval", "related_to"),
    ("data-augmentation", "regularization", "is_a"),
    ("cross-validation", "generalization", "related_to"),
    ("feature-engineering", "machine-learning", "part_of"),
    ("bias-variance-tradeoff", "generalization", "related_to"),
    ("bias-variance-tradeoff", "overfitting", "related_to"),
    ("learning-rate", "gradient-descent", "part_of"),
    ("contrastive-learning", "self-supervised-learning", "is_a"),
    ("zero-shot-learning", "transfer-learning", "related_to"),
    ("few-shot-learning", "transfer-learning", "is_a"),
    ("multimodal-learning", "deep-learning", "is_a"),
    ("multimodal-learning", "computer-vision", "related_to"),
    ("multimodal-learning", "natural-language-processing", "related_to"),

    # datasets / benchmarks
    ("imagenet", "image-classification", "used_in"),
    ("mnist", "image-classification", "used_in"),
    ("cifar-10", "image-classification", "used_in"),
    ("coco", "object-detection", "used_in"),
    ("coco", "instance-segmentation", "used_in"),
    ("squad", "question-answering", "used_in"),
    ("common-crawl", "large-language-model", "used_in"),
    ("imagenet", "resnet", "used_in"),

    # applications
    ("machine-learning", "recommender-system", "used_in"),
    ("deep-learning", "recommender-system", "used_in"),
    ("computer-vision", "autonomous-driving", "used_in"),
    ("reinforcement-learning", "autonomous-driving", "used_in"),
    ("object-detection", "autonomous-driving", "used_in"),
    ("speech-recognition", "natural-language-processing", "related_to"),
    ("recurrent-neural-network", "speech-recognition", "used_in"),
    ("transformer", "speech-recognition", "used_in"),
    ("anomaly-detection", "unsupervised-learning", "related_to"),
    ("knowledge-graph", "recommender-system", "used_in"),
    ("embedding", "recommender-system", "used_in"),

    # ---------- 补充：更丰富的交叉关系 ----------
    ("attention-mechanism", "natural-language-processing", "used_in"),
    ("attention-mechanism", "deep-learning", "used_in"),
    ("attention-mechanism", "sequence-to-sequence", "used_in"),
    ("self-attention", "transformer", "part_of"),
    ("multi-head-attention", "transformer", "part_of"),
    ("convolutional-neural-network", "object-detection", "used_in"),
    ("convolutional-neural-network", "semantic-segmentation", "used_in"),
    ("resnet", "computer-vision", "used_in"),
    ("resnet", "deep-learning", "is_a"),
    ("lstm", "natural-language-processing", "used_in"),
    ("lstm", "machine-translation", "used_in"),
    ("lstm", "deep-learning", "is_a"),
    ("lstm", "sequence-to-sequence", "used_in"),
    ("gpt", "deep-learning", "is_a"),
    ("gpt", "generative-ai", "used_in"),
    ("bert", "text-classification", "used_in"),
    ("bert", "question-answering", "used_in"),
    ("large-language-model", "language-model", "is_a"),
    ("large-language-model", "generative-ai", "used_in"),
    ("transformer", "generative-ai", "used_in"),
    ("diffusion-model", "deep-learning", "is_a"),
    ("generative-adversarial-network", "deep-learning", "is_a"),
    ("variational-autoencoder", "deep-learning", "is_a"),
    ("graph-neural-network", "artificial-neural-network", "is_a"),
    ("deep-learning", "reinforcement-learning", "related_to"),
    ("deep-q-network", "reinforcement-learning", "is_a"),
    ("ppo", "reinforcement-learning", "is_a"),
    ("actor-critic", "policy-gradient", "related_to"),
    ("markov-decision-process", "q-learning", "used_in"),
    ("markov-decision-process", "deep-q-network", "used_in"),
    ("coco", "image-captioning", "used_in"),
    ("coco", "semantic-segmentation", "used_in"),
    ("imagenet", "convolutional-neural-network", "used_in"),
    ("imagenet", "vision-transformer", "used_in"),
    ("mnist", "convolutional-neural-network", "used_in"),
    ("squad", "bert", "used_in"),
    ("common-crawl", "gpt", "used_in"),
    ("common-crawl", "bert", "used_in"),
    ("tokenization", "language-model", "part_of"),
    ("principal-component-analysis", "feature-engineering", "used_in"),
    ("cross-validation", "supervised-learning", "used_in"),
    ("gradient-descent", "linear-regression", "used_in"),
    ("logistic-regression", "gradient-descent", "used_in"),
    ("decision-tree", "overfitting", "related_to"),
    ("dropout", "overfitting", "related_to"),
    ("batch-normalization", "deep-learning", "used_in"),
    ("adam", "deep-learning", "used_in"),
    ("backpropagation", "deep-learning", "used_in"),
    ("gradient-descent", "deep-learning", "used_in"),
    ("image-captioning", "transformer", "used_in"),
    ("image-captioning", "convolutional-neural-network", "used_in"),
    ("vision-transformer", "image-classification", "used_in"),
    ("anomaly-detection", "machine-learning", "used_in"),
    ("autonomous-driving", "deep-learning", "used_in"),
    ("speech-recognition", "deep-learning", "used_in"),
    ("sequence-to-sequence", "machine-translation", "used_in"),
]
